import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

const { execFileSyncMock, getStagedDiffMock } = vi.hoisted(() => ({
  execFileSyncMock: vi.fn(),
  getStagedDiffMock: vi.fn(),
}));

vi.mock("node:child_process", () => ({
  execFileSync: execFileSyncMock,
}));

vi.mock("./git-operations.js", () => ({
  getStagedDiff: getStagedDiffMock,
}));

import { generateCommitMessage } from "./git-assist.js";

const originalEngineEntry = process.env.PI_ENGINE_ENTRY;
const originalAssistModel = process.env.BRIDGE_ASSIST_MODEL;
const originalPiModel = process.env.PI_MODEL;

describe("generateCommitMessage", () => {
  beforeEach(() => {
    execFileSyncMock.mockReset();
    getStagedDiffMock.mockReset();
    getStagedDiffMock.mockReturnValue("diff --git a/a.txt b/a.txt\n");
    delete process.env.PI_ENGINE_ENTRY;
    delete process.env.BRIDGE_ASSIST_MODEL;
    delete process.env.PI_MODEL;
  });

  afterEach(() => {
    restoreEnvVar("PI_ENGINE_ENTRY", originalEngineEntry);
    restoreEnvVar("BRIDGE_ASSIST_MODEL", originalAssistModel);
    restoreEnvVar("PI_MODEL", originalPiModel);
  });

  it("runs a headless pi --print with the prompt on stdin", () => {
    process.env.PI_ENGINE_ENTRY = "/opt/pi/bin/pi";
    execFileSyncMock.mockReturnValue("feat: generated by pi\n");

    const message = generateCommitMessage({
      projectPath: "/tmp/project",
      model: "anthropic/claude-sonnet-4",
    });

    expect(message).toBe("feat: generated by pi");
    expect(execFileSyncMock).toHaveBeenCalledWith(
      "/opt/pi/bin/pi",
      ["--print", "--no-tools", "--no-session", "--model", "anthropic/claude-sonnet-4"],
      expect.objectContaining({
        cwd: "/tmp/project",
        input:
          "Write a single Conventional Commits message in English for the staged changes below. Output only the commit message, with no quotes or explanation.\n\ndiff --git a/a.txt b/a.txt",
        encoding: "utf-8",
        maxBuffer: 1024 * 1024,
      }),
    );
  });

  it("falls back to BRIDGE_ASSIST_MODEL / PI_MODEL when no model is passed", () => {
    process.env.PI_ENGINE_ENTRY = "/opt/pi/bin/pi";
    process.env.BRIDGE_ASSIST_MODEL = "gemini-2.5-pro";
    execFileSyncMock.mockReturnValue("docs: updated readme\n");

    generateCommitMessage({ projectPath: "/tmp/project" });

    expect(execFileSyncMock).toHaveBeenCalledWith(
      "/opt/pi/bin/pi",
      expect.arrayContaining(["--model", "gemini-2.5-pro"]),
      expect.any(Object),
    );
  });

  it("fails when PI_ENGINE_ENTRY is not set", () => {
    expect(() =>
      generateCommitMessage({ projectPath: "/tmp/project" }),
    ).toThrow(/PI_ENGINE_ENTRY is not set/);
  });

  it("fails when no files are staged", () => {
    process.env.PI_ENGINE_ENTRY = "/opt/pi/bin/pi";
    getStagedDiffMock.mockReturnValue("");

    expect(() =>
      generateCommitMessage({ projectPath: "/tmp/project" }),
    ).toThrow(/Nothing to commit/);
  });

  it("fails when pi returns empty output", () => {
    process.env.PI_ENGINE_ENTRY = "/opt/pi/bin/pi";
    execFileSyncMock.mockReturnValue(" \n");

    expect(() =>
      generateCommitMessage({ projectPath: "/tmp/project" }),
    ).toThrow(/empty output/);
  });
});

function restoreEnvVar(key: string, value: string | undefined): void {
  if (value === undefined) {
    delete process.env[key];
    return;
  }
  process.env[key] = value;
}
